# Plugin "Get IP" OCSInventory
# Author CARNET
# Original : Valentin COSSE & Valentin DEVILLE

$ripeOrg     = [String]::Empty;
$ripeNetName = [String]::Empty;

$ipify = Invoke-RestMethod -Uri "https://api.ipify.org?format=text";
$ripeWhois = (Invoke-RestMethod -Uri "https://stat.ripe.net/data/whois/data.json?resource=$ipify").data.records;

for ($ripeKey=0; $ripeKey -le $ripeWhois.value.Count; $ripeKey++) {
    if ($ripeWhois.key[$ripeKey] -eq "descr") {
        $ripeOrg += $ripeWhois.value[$ripeKey] +", ";
    }
    elseif ($ripeWhois.key[$ripeKey] -eq "netname") {
        $ripeNetName += $ripeWhois.value[$ripeKey] +", ";
    }
}

$ripeOrg     = $ripeOrg.TrimEnd();
$ripeNetName = $ripeNetName.TrimEnd();

if ($ripeOrg.Length -gt 0) { if ($ripeOrg.Substring($ripeOrg.Length-1,1) -eq ",") { $ripeOrg = $ripeOrg.Substring(0,$ripeOrg.Length-1) } }
if ($ripeNetName -gt 0) { if ($ripeNetName.Substring($ripeNetName.Length-1,1) -eq ",") { $ripeNetName = $ripeNetName.Substring(0,$ripeNetName.Length-1) } }

$xml = '<LASTPUBLICIP>'
$xml += '<IP>' + $ipify + '</IP>'
$xml += '<CITY>' + $ripeNetName + '</CITY>'
$xml += '<ORG>' + $ripeOrg + '</ORG>'
$xml += '</LASTPUBLICIP>'

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8;
[Console]::WriteLine($xml);

# SIG # Begin signature block
# MIIX3gYJKoZIhvcNAQcCoIIXzzCCF8sCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU7pDkrlrP3TPjvGrQEqU/7vAf
# aCKgghMWMIID7jCCA1egAwIBAgIQfpPr+3zGTlnqS5p31Ab8OzANBgkqhkiG9w0B
# AQUFADCBizELMAkGA1UEBhMCWkExFTATBgNVBAgTDFdlc3Rlcm4gQ2FwZTEUMBIG
# A1UEBxMLRHVyYmFudmlsbGUxDzANBgNVBAoTBlRoYXd0ZTEdMBsGA1UECxMUVGhh
# d3RlIENlcnRpZmljYXRpb24xHzAdBgNVBAMTFlRoYXd0ZSBUaW1lc3RhbXBpbmcg
# Q0EwHhcNMTIxMjIxMDAwMDAwWhcNMjAxMjMwMjM1OTU5WjBeMQswCQYDVQQGEwJV
# UzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xMDAuBgNVBAMTJ1N5bWFu
# dGVjIFRpbWUgU3RhbXBpbmcgU2VydmljZXMgQ0EgLSBHMjCCASIwDQYJKoZIhvcN
# AQEBBQADggEPADCCAQoCggEBALGss0lUS5ccEgrYJXmRIlcqb9y4JsRDc2vCvy5Q
# WvsUwnaOQwElQ7Sh4kX06Ld7w3TMIte0lAAC903tv7S3RCRrzV9FO9FEzkMScxeC
# i2m0K8uZHqxyGyZNcR+xMd37UWECU6aq9UksBXhFpS+JzueZ5/6M4lc/PcaS3Er4
# ezPkeQr78HWIQZz/xQNRmarXbJ+TaYdlKYOFwmAUxMjJOxTawIHwHw103pIiq8r3
# +3R8J+b3Sht/p8OeLa6K6qbmqicWfWH3mHERvOJQoUvlXfrlDqcsn6plINPYlujI
# fKVOSET/GeJEB5IL12iEgF1qeGRFzWBGflTBE3zFefHJwXECAwEAAaOB+jCB9zAd
# BgNVHQ4EFgQUX5r1blzMzHSa1N197z/b7EyALt0wMgYIKwYBBQUHAQEEJjAkMCIG
# CCsGAQUFBzABhhZodHRwOi8vb2NzcC50aGF3dGUuY29tMBIGA1UdEwEB/wQIMAYB
# Af8CAQAwPwYDVR0fBDgwNjA0oDKgMIYuaHR0cDovL2NybC50aGF3dGUuY29tL1Ro
# YXd0ZVRpbWVzdGFtcGluZ0NBLmNybDATBgNVHSUEDDAKBggrBgEFBQcDCDAOBgNV
# HQ8BAf8EBAMCAQYwKAYDVR0RBCEwH6QdMBsxGTAXBgNVBAMTEFRpbWVTdGFtcC0y
# MDQ4LTEwDQYJKoZIhvcNAQEFBQADgYEAAwmbj3nvf1kwqu9otfrjCR27T4IGXTdf
# plKfFo3qHJIJRG71betYfDDo+WmNI3MLEm9Hqa45EfgqsZuwGsOO61mWAK3ODE2y
# 0DGmCFwqevzieh1XTKhlGOl5QGIllm7HxzdqgyEIjkHq3dlXPx13SYcqFgZepjhq
# IhKjURmDfrYwggSjMIIDi6ADAgECAhAOz/Q4yP6/NW4E2GqYGxpQMA0GCSqGSIb3
# DQEBBQUAMF4xCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3Jh
# dGlvbjEwMC4GA1UEAxMnU3ltYW50ZWMgVGltZSBTdGFtcGluZyBTZXJ2aWNlcyBD
# QSAtIEcyMB4XDTEyMTAxODAwMDAwMFoXDTIwMTIyOTIzNTk1OVowYjELMAkGA1UE
# BhMCVVMxHTAbBgNVBAoTFFN5bWFudGVjIENvcnBvcmF0aW9uMTQwMgYDVQQDEytT
# eW1hbnRlYyBUaW1lIFN0YW1waW5nIFNlcnZpY2VzIFNpZ25lciAtIEc0MIIBIjAN
# BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAomMLOUS4uyOnREm7Dv+h8GEKU5Ow
# mNutLA9KxW7/hjxTVQ8VzgQ/K/2plpbZvmF5C1vJTIZ25eBDSyKV7sIrQ8Gf2Gi0
# jkBP7oU4uRHFI/JkWPAVMm9OV6GuiKQC1yoezUvh3WPVF4kyW7BemVqonShQDhfu
# ltthO0VRHc8SVguSR/yrrvZmPUescHLnkudfzRC5xINklBm9JYDh6NIipdC6Anqh
# d5NbZcPuF3S8QYYq3AhMjJKMkS2ed0QfaNaodHfbDlsyi1aLM73ZY8hJnTrFxeoz
# C9Lxoxv0i77Zs1eLO94Ep3oisiSuLsdwxb5OgyYI+wu9qU+ZCOEQKHKqzQIDAQAB
# o4IBVzCCAVMwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAO
# BgNVHQ8BAf8EBAMCB4AwcwYIKwYBBQUHAQEEZzBlMCoGCCsGAQUFBzABhh5odHRw
# Oi8vdHMtb2NzcC53cy5zeW1hbnRlYy5jb20wNwYIKwYBBQUHMAKGK2h0dHA6Ly90
# cy1haWEud3Muc3ltYW50ZWMuY29tL3Rzcy1jYS1nMi5jZXIwPAYDVR0fBDUwMzAx
# oC+gLYYraHR0cDovL3RzLWNybC53cy5zeW1hbnRlYy5jb20vdHNzLWNhLWcyLmNy
# bDAoBgNVHREEITAfpB0wGzEZMBcGA1UEAxMQVGltZVN0YW1wLTIwNDgtMjAdBgNV
# HQ4EFgQURsZpow5KFB7VTNpSYxc/Xja8DeYwHwYDVR0jBBgwFoAUX5r1blzMzHSa
# 1N197z/b7EyALt0wDQYJKoZIhvcNAQEFBQADggEBAHg7tJEqAEzwj2IwN3ijhCcH
# bxiy3iXcoNSUA6qGTiWfmkADHN3O43nLIWgG2rYytG2/9CwmYzPkSWRtDebDZw73
# BaQ1bHyJFsbpst+y6d0gxnEPzZV03LZc3r03H0N45ni1zSgEIKOq8UvEiCmRDoDR
# EfzdXHZuT14ORUZBbg2w6jiasTraCXEQ/Bx5tIB7rGn0/Zy2DBYr8X9bCT2bW+IW
# yhOBbQAuOA2oKY8s4bL0WqkBrxWcLC9JG9siu8P+eJRRw4axgohd8D20UaF5Mysu
# e7ncIAkTcetqGVvP6KUwVyyJST+5z3/Jvz4iaGNTmr1pdKzFHTx/kuDDvBzYBHUw
# ggUZMIIEAaADAgECAhANucYRs6r/dGB7AgZevKrFMA0GCSqGSIb3DQEBCwUAMGUx
# CzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3
# dy5kaWdpY2VydC5jb20xJDAiBgNVBAMTG0RpZ2lDZXJ0IEFzc3VyZWQgSUQgUm9v
# dCBDQTAeFw0xNDExMTgxMjAwMDBaFw0yNDExMTgxMjAwMDBaMG0xCzAJBgNVBAYT
# Ak5MMRYwFAYDVQQIEw1Ob29yZC1Ib2xsYW5kMRIwEAYDVQQHEwlBbXN0ZXJkYW0x
# DzANBgNVBAoTBlRFUkVOQTEhMB8GA1UEAxMYVEVSRU5BIENvZGUgU2lnbmluZyBD
# QSAzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAquLnIC+sEJX6zSTl
# +KDf9aKtn7yzyeH4H8Q+5JZBbbvnA/AMFHG9pjhRt1A5pzn2Qm3iXMSe/6t41b1n
# AyHpbgTMRt/FhySUn/3WLAVhg5Oy9eF3ZCq61VDzttpv0Iu8fz5rAO5cszS/UMD4
# yPB9V350CkivbUhMi2+KXiO+dstdhHhWO4hnm9GIYKIIRAeIiabD8twq4HNswpuE
# JvcUPotKqGkI9JOJ6B9p67QqdTILGY98swy4WuRGtGRrx9BQm/CAtE81cZ8gf1nI
# VGbszTMT3wkyhRACYWg8tJIkYLqg0ry1xwe9/FDqNGAIHwKhjx+3LP1apkmAuTn6
# WUn5GQIDAQABo4IBuzCCAbcwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8E
# BAMCAYYwEwYDVR0lBAwwCgYIKwYBBQUHAwMweQYIKwYBBQUHAQEEbTBrMCQGCCsG
# AQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wQwYIKwYBBQUHMAKGN2h0
# dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RD
# QS5jcnQwgYEGA1UdHwR6MHgwOqA4oDaGNGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNv
# bS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcmwwOqA4oDaGNGh0dHA6Ly9jcmw0
# LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcmwwPQYDVR0g
# BDYwNDAyBgRVHSAAMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2ljZXJ0
# LmNvbS9DUFMwHQYDVR0OBBYEFDIKwQzBaD5XqC35eSLljpzpRI4yMB8GA1UdIwQY
# MBaAFEXroq/0ksuCMS1Ri6enIZ3zbcgPMA0GCSqGSIb3DQEBCwUAA4IBAQBErVAK
# Ga8D4fOknsozyzRElbTq3fi5SLXlapnDtwGOrtXEcx59Wgj9Gb8gTMUBu8iy2xDJ
# 2SsN3c5xPNxbrrlnS++9sESYuGEp3Kh6c7IUvXQ/MFzDecAM9Fbcs/7hiXhFpYfo
# WSiPRIttBj+xNsQw7nRsVMvEA9dveBrjbEN2FUaeIklZl0043htM0nyWG/y61+l6
# GDAXLNWGiS7Qmhk+NfLGK75RSWdJHWUhr0IiTg1NDxoC6ZuCduf8irB7dVZN6j+Q
# D4onBFUwE3pTof72XqL2STlUXwPJi2o1zjCoAuBAFe0VlRAdBmPv742jmuHBWmCa
# MYSXufCLkCpqy8ciMIIFXDCCBESgAwIBAgIQCKy6iNFIWpN8dVd25lrgKzANBgkq
# hkiG9w0BAQsFADBtMQswCQYDVQQGEwJOTDEWMBQGA1UECBMNTm9vcmQtSG9sbGFu
# ZDESMBAGA1UEBxMJQW1zdGVyZGFtMQ8wDQYDVQQKEwZURVJFTkExITAfBgNVBAMT
# GFRFUkVOQSBDb2RlIFNpZ25pbmcgQ0EgMzAeFw0xODA5MTEwMDAwMDBaFw0yMTA5
# MTUxMjAwMDBaMIGoMQswCQYDVQQGEwJIUjEPMA0GA1UEBxMGWmFncmViMTwwOgYD
# VQQKDDNIcnZhdHNrYSBha2FkZW1za2EgaSBpc3RyYcW+aXZhxI1rYSBtcmXFvmEg
# LSBDQVJORVQxDDAKBgNVBAsTA1JJUzE8MDoGA1UEAwwzSHJ2YXRza2EgYWthZGVt
# c2thIGkgaXN0cmHFvml2YcSNa2EgbXJlxb5hIC0gQ0FSTkVUMIIBIjANBgkqhkiG
# 9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyoljHtVmlBqaR26r8ndri5/fVFv7EAcPaPom
# /3Q1a0/dPmXyh19u4QGYRciqkBPFYEl4e9g8oBhSRfmrTj3/M2tNphY6/reOX/26
# Khdpa5OlSPhGulXgu6JTgq4w526wvpEKlYtofCzcdeXyC494YuRq4Ue4anH8QtVI
# NPt0WMJr9i1UdV560z6BMZ/uE2GAPhep0tQ7887cTMRH4pS0Sf7KVMc4WODr2iWY
# 51bAp3aIBm1jwDm8fnTw9nYjmJLCbcL1eQLYsJd02/D6OpDNRx5OUgT1ldwyXZ0E
# ol6QHUIm3GypdIOrixe2ngO6ZRFb+ubrqBfzdC0Uvu2FhKaBCQIDAQABo4IBujCC
# AbYwHwYDVR0jBBgwFoAUMgrBDMFoPleoLfl5IuWOnOlEjjIwHQYDVR0OBBYEFA1k
# yD63fDwWSMu1J9nmGm1kofzwMA4GA1UdDwEB/wQEAwIHgDATBgNVHSUEDDAKBggr
# BgEFBQcDAzB7BgNVHR8EdDByMDegNaAzhjFodHRwOi8vY3JsMy5kaWdpY2VydC5j
# b20vVEVSRU5BQ29kZVNpZ25pbmdDQTMuY3JsMDegNaAzhjFodHRwOi8vY3JsNC5k
# aWdpY2VydC5jb20vVEVSRU5BQ29kZVNpZ25pbmdDQTMuY3JsMEwGA1UdIARFMEMw
# NwYJYIZIAYb9bAMBMCowKAYIKwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2ljZXJ0
# LmNvbS9DUFMwCAYGZ4EMAQQBMHYGCCsGAQUFBwEBBGowaDAkBggrBgEFBQcwAYYY
# aHR0cDovL29jc3AuZGlnaWNlcnQuY29tMEAGCCsGAQUFBzAChjRodHRwOi8vY2Fj
# ZXJ0cy5kaWdpY2VydC5jb20vVEVSRU5BQ29kZVNpZ25pbmdDQTMuY3J0MAwGA1Ud
# EwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggEBAEO9vfUTxbiraqDz7i3s71mgC6nS
# En0OffNrmuwW38pn/yO69EOOkj8qhnBITSiZiRc0Csmo2FjZYHwcGiH1kdvbT+9N
# XwWXfV5Ierm7fgLBvXUCRCuN8nzRQAksywOB4u1CI0BfKUhx1gBlblEoamx/gB/j
# Zo72dxzOdwGrVIgEt91avqM8F5K5SYsVHD7k1bCIo3OwO+nWWo7iHWW/9O49Ezsm
# HIl1W83WcNnxnaXt13n/AD64Df+GJ0pZ3kDIjRqChLeGb9jsjbz7LDcD/41nhhhF
# tiB/0oYOaxXEdE+ul2wkEH60jhxTGE5SQiF0qSjiQAtciVskTV6HK1FGnv0xggQy
# MIIELgIBATCBgTBtMQswCQYDVQQGEwJOTDEWMBQGA1UECBMNTm9vcmQtSG9sbGFu
# ZDESMBAGA1UEBxMJQW1zdGVyZGFtMQ8wDQYDVQQKEwZURVJFTkExITAfBgNVBAMT
# GFRFUkVOQSBDb2RlIFNpZ25pbmcgQ0EgMwIQCKy6iNFIWpN8dVd25lrgKzAJBgUr
# DgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMx
# DAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkq
# hkiG9w0BCQQxFgQUMmchN7COQ2ZThrVPg2vJns2Gj04wDQYJKoZIhvcNAQEBBQAE
# ggEAxJ1v7RotU1tj/89AOm/I+ZhfScDKLAV6FzVNIf3zdQcCT17CvvjQMftgvItb
# m9bDOSVaMJPdwRbHeK0MTypWRe9wIHM/S0hkFaB3KkNrUhf1Uhem0ksrrjLcMFuc
# PuT4OGtjU4PPWlm2ubtcM3GP4764YU5uzTsWGq15nuUhRAZLyCYbsfQYl3cKjEZy
# qPFIvy/6ws4ax9FDY+cjoSUjAOtwLAbPS9WXQ2d5tbCbPT2WjTM1liEwenlDLpPK
# txdq5n3lpbKBamTddR8DsbQR4GJsPo6mtXRdIpURRfO55LBBJb/BXJn9E3OfU5ql
# e/Wy98bV42AbwCDL/vca6/8k06GCAgswggIHBgkqhkiG9w0BCQYxggH4MIIB9AIB
# ATByMF4xCzAJBgNVBAYTAlVTMR0wGwYDVQQKExRTeW1hbnRlYyBDb3Jwb3JhdGlv
# bjEwMC4GA1UEAxMnU3ltYW50ZWMgVGltZSBTdGFtcGluZyBTZXJ2aWNlcyBDQSAt
# IEcyAhAOz/Q4yP6/NW4E2GqYGxpQMAkGBSsOAwIaBQCgXTAYBgkqhkiG9w0BCQMx
# CwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xOTA2MjgxMTU1MzNaMCMGCSqG
# SIb3DQEJBDEWBBTA7FKtGCsHUPmQwJ/ZGpdw+F3SxzANBgkqhkiG9w0BAQEFAASC
# AQBasIjUyGnYNPv6Bl4HA2jfxat/yKXx2BHfySII5RFd5fIYZbBd7X4bx+Vggbns
# 6w89cXQphxHWDNn71ykE1HbGPZALMsVdSMLMQg4chys+6oRXFP6rrIGVhvuanzJn
# DsQE/ZNAvHRAgSDw70ggpmduCPDkM7zPIn9iepwxmenn6g8fDTr408RWeZT7Pap9
# 3CoweLHCyj/1kizXYpnE1hIDx57WBR8W32QMDjoi4nLNjAw3X8QqFdzpz1tKKpVz
# vid8PDo7rjV2r3UgfzzscXmxgVXOdEFqQ9F6+AYX/hOe7DsAwBhSDjiWM44k++NH
# ShivBJoyC0xgMhGE4nhp9PkS
# SIG # End signature block
